### ISSUE TITLE
feat(connector-xdai): add interval to pollForTxReceipt

### ISSUE THREAD

**Issue by Zzocker** [hyperledger/cactus#1078]
**Is your feature request related to a problem? Please describe.**
While waiting for transaction receipt for a given txHash (contract running ropsten test network, node connected via infura ) I saw more then  500 eth_getTransactionReceipt calls in my infura dashboard. 

**Describe the solution you'd like**
Rather then doing a while loop ([here](https://github.com/hyperledger/cactus/blob/526c4fb122e519a60d742b58e48003b06b9522b4/packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts#L488)) continuously,it should loop at given interval. this interval can be passed as a field to `ConsistencyStrategy`.

**Describe alternatives you've considered**
Implemented above described using a new instance of Web3

**Comment by petermetz** [comment]
@Zzocker FYI you can link together (for future reference) a PR of yours with a corresponding issue so that the issue automatically gets closed as soon as the PR gets merged.
The way to do it is to use the `Fixes #ISSUE_NUMBER` syntax. More info here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
