### ISSUE TITLE
Support tools to build `test net` for demo apps

### ISSUE THREAD

**Issue by sfuji822** [hyperledger/cactus#181]
**Is your feature request related to a problem? Please describe.**
Providing sample application is important for demonstration purpose.
But it is also needed to keep separated such demo app from main framework.

**Describe the solution you'd like**
We should provide support tool to build `test net` for specific Ledger platform to work with sample web application build on top of Cactus SDK.

**Describe alternatives you've considered**
Providing test case on each Cactus components, but it is merely work for unit tests.

**Additional context**
I am considering to provide solution as docker-compose environment which is  easy to build and run without deep knowledge.

**Comment by petermetz** [comment]
@sfuji822 Is it required in the scope of this issue to have the test nets run multiple nodes or is it okay to have single node test nets?

Just asking because for the integration tests we have single node test nets that you can pull up via code, like this one brings up a Besu test ledger that is then used for ledger testing:
packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts

And the limitation of this is that it single node ledger only, so if we need multiple nodes in the test net then it is not a good fit in it's current form (could be improved of course).

**Comment by RafaelAPB** [comment]
I think it is very relevant to us to be able to bootstrap **both** single node and multiple node test networks. Several features we are developing can be trivially tested with a single node network; but in production, many networks will have multiple nodes, and we want to test those interactions.

**Comment by sfuji822** [comment]
@petermetz , I did not any preference on the number of node since my expectation on this feature is simply tasks on trying Cactus at docker-based playground. takeutak or I will submit related PR soon.

**Comment by sfuji822** [comment]
@RafaelAPB , thanks for you comment. I like to implement this as minimal set at first, but I also agree with you on the potential needs on tricky configuration and we may extend it after first version.

**Comment by RafaelAPB** [comment]
@sfuji822, you're welcome! Are you planning to extend the test ledger classes, then? It does require new images to implement multi-node networks, is that correct?

**Comment by petermetz** [comment]
Closing as per what was done and described in #240

**Comment by petermetz** [comment]
> @sfuji822, you're welcome! Are you planning to extend the test ledger classes, then? It does require new images to implement multi-node networks, is that correct?

@RafaelAPB Now I can answer this (after having seen the PR) This does not use/work with the `FabricTestLedger` class so we'll have to pick that up in a separate thread/issue.
