### ISSUE TITLE
fix(plugin-ledger-connector-iroha): running the container image locally fails

### ISSUE THREAD

**Issue by izuru0** [hyperledger/cactus#1874]
**Describe the bug**

when trying to run iroha connector container locally by following [README](https://github.com/hyperledger/cactus/tree/main/packages/cactus-plugin-ledger-connector-iroha#buildingrunning-the-container-image-locally), command `docker run` returns error.

**To Reproduce**

first:

```
yarn run configure
yarn run build:dev:backend
DOCKER_BUILDKIT=1 docker build -f ./packages/cactus-plugin-ledger-connector-iroha/Dockerfile . -t cplcb
```

then:

```
docker run \
  --rm \
  --publish 3000:3000 \
  --publish 4000:4000 \
  --publish 5000:5000 \
  --env PLUGINS='[{"packageName": "@hyperledger/cactus-plugin-ledger-connector-iroha", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL", "action": "org.hyperledger.cactus.plugin_import_action.INSTALL",  "options": {"rpcApiHttpHost": "http://localhost:8545", "instanceId": "some-unique-iroha-connector-instance-id"}}]' \
  cplcb
```

**Expected behavior**

container runs.

**Logs/Stack traces**

[docker-command-log.txt](https://github.com/hyperledger/cactus/files/8118278/docker-command-log.txt)

**Cloud provider or hardware configuration:**

local pc

**Operating system name, version, build:**

```sh
/tmp/tryiroha/cactus$ printf "$(uname -srm)\n$(cat /etc/os-release)\n"
Linux 5.13.0-30-generic x86_64
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
/tmp/tryiroha/cactus$ node --version
v16.13.1
/tmp/tryiroha/cactus$ docker --version
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
/tmp/tryiroha/cactus$ 
```

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

```
/tmp/tryiroha/cactus$ git rev-parse --short HEAD
a8734bf0
```
**Hyperledger Cactus Plugins/Connectors Used**

iroha

**Comment by izuru0** [comment]
@petermetz are there any workaround for this?

**Comment by petermetz** [comment]
@izuru0 Apologies for the slow response, I'm investigating this and it's looking like one of those cascading/domino effect bugs where multiple things came together to wreak havoc...
A part of the plot has been uncovered and documented here, but I'm working on more of it: https://github.com/hyperledger/cactus/issues/1951

**Comment by petermetz** [comment]
One more thing (more of a note to self) is that you'll also need the authorization configuration in the env variables (if that's the preferred way for you to provide the config) so something like this for **testing & development** should work better:

(this still won't work as of today until the other fixes are in place but I wanted to make not anyway because it's one more clue)

```sh
docker run \
  --rm \
  --publish 3000:3000 \
  --publish 4000:4000 \
  --publish 5000:5000 \
  --env AUTHORIZATION_CONFIG_JSON="{}"\
  --env AUTHORIZATION_PROTOCOL=NONE \
  --env PLUGINS='[{"packageName": "@hyperledger/cactus-plugin-ledger-connector-iroha", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL", "action": "org.hyperledger.cactus.plugin_import_action.INSTALL",  "options": {"rpcApiHttpHost": "http://localhost:8545", "instanceId": "some-unique-iroha-connector-instance-id"}}]' \
  cplcb:latest
```

**Comment by jagpreetsinghsasan** [comment]
> One more thing (more of a note to self) is that you'll also need the authorization configuration in the env variables (if that's the preferred way for you to provide the config) so something like this for **testing & development** should work better:
> 
> (this still won't work as of today until the other fixes are in place but I wanted to make not anyway because it's one more clue)
> 
> ```shell
> docker run \
>   --rm \
>   --publish 3000:3000 \
>   --publish 4000:4000 \
>   --publish 5000:5000 \
>   --env AUTHORIZATION_CONFIG_JSON="{}"\
>   --env AUTHORIZATION_PROTOCOL=NONE \
>   --env PLUGINS='[{"packageName": "@hyperledger/cactus-plugin-ledger-connector-iroha", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL", "action": "org.hyperledger.cactus.plugin_import_action.INSTALL",  "options": {"rpcApiHttpHost": "http://localhost:8545", "instanceId": "some-unique-iroha-connector-instance-id"}}]' \
>   cplcb:latest
> ```

This wasn't working for me

> DOCKER_BUILDKIT=1 docker build -f ./packages/cactus-plugin-ledger-connector-iroha/Dockerfile . -t cplcb

I tried running the plain `cactus-cmd-api-server` with the similar above command, and even that wasn't working.
So I had to create a sample config.json with this field specifically mentioned `grpcMtlsEnabled` set to false.
Then only I could make the api-server running using this command
```shell
docker run --rm --publish 3000:3000 --publish 4000:4000 --mount type=bind,source="$(pwd)"/.config.json,target=/config.json --env AUTHORIZATION_CONFIG_JSON="{}"  --env AUTHORIZATION_PROTOCOL=NONE --env CONFIG_FILE=/config.json cas
```
And the iroha plugin was not able to run (in my case) with the error `run-time-error module not found`
Currently looking into this (because the container actually contains the run-time-error module under node_modules, as shown in the below screenshot, thus investigating)

![image](https://user-images.githubusercontent.com/56861721/201019243-9e24af8a-63e5-4b77-879e-d7348d19e6a5.png)
![image](https://user-images.githubusercontent.com/56861721/201019571-c994d4aa-7770-4368-8e27-0ae066cf9c02.png)
