### ISSUE TITLE
docs(whitepaper): terminology for assets and interaction types

### ISSUE THREAD

**Issue by DOBEN** [hyperledger/cactus#192]
### Description
I want to update the white paper focusing on following changes (an explanatory draft of the proposed changes are given in the attached document):
https://chat.hyperledger.org/file-upload/YjNwc6wnBypHyMBvJ/Suggestions%20white%20paper.pdf?download

1. Defining and using consistent terminology with respect to the current names "data", "asset", and "data asset" in the example use case section. The following naming convention is proposed:
- FA = fungible asset (alternative naming: value token/coin T) – cannot be duplicated on different ledgers
- NFA = non-fungible asset (alternative naming: asset A) – cannot be duplicated on different ledgers
- D = data – can be duplicated on different ledgers
2. Defining three ledger interaction types (ledger transfer/ledger coordination/ledger entry-point coordination)
3. Using the definitions from 1. and 2. to create a table to classify and order all mentioned example use cases.
4. A section about "burning of tokens" and use cases in the appendix.

This table acts as a building block to describe the different flavors of how cactus can be used. Real-world use cases will likely be built on these simple foundation blocks leveraging a mix of them simultaneously.  

As a new person who is considering using cactus in a concrete business use case, this table will help to identify relevant example use cases that are aligned with a given concrete business use case.

**Comment by petermetz** [comment]
@DOBEN Thank you for helping out, as mentioned in the call this week, I'm in general in support of all possible improvements! 
As for me, I will need some more time to read it thoroughly and pick on the details (as I'm sure others will too), but in the meantime I have a recommendation related to administrative side of things: 

The github issue/PR name should be something more specific that gets to the heart of what is the proposed change to reduce the cognitive load required when there are multiple issues circulating with similar titles. 
What I mean is that `Whitepaper improvements` could be replaced with `docs(whitepaper): terminology for assets and interaction types` so that we don't get confused if there are multiple issues opened by different people (all of them being some sort of improvement to the whitepaper). 
This is not the case yet, but as the community grows we expect (and hope) to have this as a problem. :-)

**Comment by DOBEN** [comment]
Yes, good point. I changed the title :).

**Comment by Mr1262** [comment]
BTC WALLET MMM

**Comment by DOBEN** [comment]
Thank you for the helpful comments in this thread and the thread related to the pull request #216. I will close this issue since it was addressed and merged in #216.
