### ISSUE TITLE
feat(core-api): HTLC coordinator

### ISSUE THREAD

**Issue by kikoncuo** [hyperledger/cactus#603]
To be defined if this needs to be separated into another plugin.

One of the main ideas around Cactus is that it should be running automating the interactions between different nodes.
We have working HTLCs which can work on different networks but right now they need to be executed manually.
We need a plugin which can be ran by Cactus users which automates inter-node interactions.
As a first instance, we can create the HTLC coordinator, which would be the plugin in charge of monitoring a network and automate all HTLC functionality.

After an HTLC is created, this plugin would be in charge of monitoring and automating claims and refunds.
The process would be:
1. The HTLC is created manually on DLT1 using the correspondent HTLC plugin
2. The matching HTLC is created manually on DLT2 using the correspondent HTLC plugin
3. The HTLC coordinator plugin ran by user 1 (In DLT1) detects the second contract has been deployed and executes the claim on DLT2
4. The HTLC coordinator plugin ran by user 2 (In DLT2) detects the second contract has been claimed and uses the now disclosed secret to claim his asset on DLT1

Optionally the HTLC coordinator could handle the HTLC creation process to minimize time conflicts around refund timings

Acceptance criteria:
* When an HTLC is created, the HTLC coordinator monitors event/transactions
* When a matching HTLC is created, the coordinator claims the resolution
* When an HTLC secret is disclosed, the HTLC coordinators uses it to release tokens

Parent: feat(core-api): atomic swaps with HTLCs #510

**Comment by petermetz** [comment]
Note to self: The core underlying question here will be about storing state (if any) for the implementation of this. So far we have intentionally steered clear of having any state within the plugins/API server and once we make that jump things will be significantly more complex so whatever we decide here must be carefully thought out. 
https://github.com/hyperledger/cactus/issues/348 is highly relevant here and possibly even a pre-condition for this issue (#603)

**Comment by jordigiam** [comment]
In this scenario Bob start the flow: 

<img width="1048" alt="Captura de pantalla 2021-04-14 a las 16 53 21" src="https://user-images.githubusercontent.com/78140052/115706712-3cfee580-a36e-11eb-9c73-b80e29c4734d.png">


<img width="1062" alt="Captura de pantalla 2021-04-14 a las 16 52 29" src="https://user-images.githubusercontent.com/78140052/115706549-12149180-a36e-11eb-86b4-2e4f4f03b1bf.png">

**Comment by sfuji822** [comment]
I apologize my response took longer than expected.

I assumed you want to implement Atomic Swap with coordination by the HTLC Coordinator on the choice of HTLC contracts and monitoring the transaction of the counterparty.

First of all, we need to decide whether HTLC contracts should be reusable or not.
Those contract(s) could be reusable since the HTLC Coordinator is the actual entity to interact with the HTLC contracts.
I am OK without reusable HTLCs because the Coordinator can decide when HTLC is instantiated (or deployed?).

I believe HTLC instantiations are executed at the beginning of the flow since involving party (Alice, Bob, and the HTLC Coordinator) must know the HTLC addresses for starting Atomic Swap.

Normal HTLC has the following functions:
- Receive transfer funds request to the receiver, which is timed-hash-locked with hash-value and expiration time
- Accept execute transfer(=withdrawal) triggered by the receiver only when given secret-code(origin of the hash-value) is valid
- Accept refund by originator after give expiration time has passed

Known implementation of Atomic Swaps executes the following transactions:
1. invoke HTLC-1 with hashed-time-lock with expiration-1 by Bob
2. invoke HTLC-2 with hashed-time-lock with expiration-2 by Alice #Note expiration-2 must come first
3. Invoke HTLC-2 by Bob to withdraw funds which are locked along with secret-code
4. Invoke HTLC-1 by Alice to withdraw funds that are locked using observed secret-code

[If Bob could not observe Alice's transaction on HTLC-2]
3. Invoke HTLC-1 by Bob to cancel the  locked transfer
4. Invoke HTLC-2 by Alice to cancel (if necessary)

Reference "The Atomic Swap Process Explained": https://komodoplatform.com/en/academy/atomic-swaps/

IMHO, if the Cactus will play the role as the intermediate on the asset trade between Alice and Bob, the HTLC address should be notified and assist in interactions with HTLC because both Alice and Bob cannot trust Cactus as fund receiver in this use case.

1. Bob instantiates HTLC Coordinator with Alice's address information
2. Bob receives the handle of the HTLC Coordinator and the address of HTLCs
3. Bob invokes HTLC-1 with hashed-time-lock with expiration-1(given by Cactus)
4. Alice invokes HTLC-2 with hashed-time-lock with expiration-2(given by Cactus)
5. Bob invokes HTLC-2 to withdraw funds from Alice
6. HTLC Coordinator invokes HTLC-1 to withdraw funds from Bob using observed transaction

Does it make sense to you? 
@kikoncuo @petermetz @jordigiam 
Cc: @takeutak

**Comment by petermetz** [comment]
@sfuji822 Thank you very much for the response! I'm forwarding it to Jagpreet who'll be taking over the PR from Jordi.
@jagpreetsinghsasan Could you please chime in on the discussion and respond to the comment from Shingo?

**Comment by jagpreetsinghsasan** [comment]
@sfuji822 Thanyou very much for the response.
I am currently going through the current implementation of the HTLC coordinator. Your opinion about the process, specially about the part of who-does-what makes more sense.
I will have some discussions around the same, with @kikoncuo and get back to you on this, as soon as possible.

**Comment by jagpreetsinghsasan** [comment]
Sorry @sfuji822 for such a late response on this.
From my understanding and discussion with @kikoncuo, Htlc coordinator referenced here and the one coded for, in the PR #953 are just sample implementations of how a coordinator should look like.
Htlc coordinator implementation for a production grade environment should be different from this and this is just as an example implementation because compromised coordinators can themselves be malicious and thus production grade implementation of a custom coordinator is prefered. The base HTLC themselves, however, can be reused from what Hyperledger Cactus offers.
For Hyperledger Cactus, the core is the HTLC themselves and not the coordinator.
Thus, we have placed the HTLC Coordinator under `extensions/` folder and not under `packages/` folder (can be checked in the PR #953)
@sfuji822, your implications of how the coordinator should execute the flow is also correct and can be picked up as another implication of a HTLC Coordinator.

CC (for reference): @petermetz

**Comment by jagpreetsinghsasan** [comment]
I have created the issue, in reference to this thread [here](https://github.com/hyperledger/cactus/issues/1180)
