### ISSUE TITLE
fix(ledger-plugin): restore the file (package.json) that was accidentally updated to its previous state

### ISSUE THREAD

**Issue by takeutak** [hyperledger/cactus#760]
**Describe the bug**

On Cactus-v0.4.0, the examples/car-trade app and the examples/electricity-trade app cannot work well because an incorrect update was made to the file (packages/package.json) by mistake due to the following PR https://github.com/hyperledger/cactus/pull/581

**To Reproduce**

I plan to post a pull-request to fix packages/package.json to solve this issue. Moreover, I'd like to add the tag of v0.4.1 in the corrected state since users cannot operate the sample applications if they use v0.4.0.

**Comment by petermetz** [comment]
@takeutak FYI: if you specify the issue number in your PR description/commit message then GH will auto-close the issue that you marked as being fixed by the commit. Something like `Fixes #760` or `Resolves #760` in the case of this issue here.

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
